# Generated by Django 5.0.1 on 2024-02-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('apartment_type', models.CharField(max_length=50, null=True, unique=True, verbose_name='Apartment Type')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=10, null=True, unique=True, verbose_name='Room Id')),
                ('room_name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Room Name')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Room Description')),
                ('amount_daily', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Amount Per Day')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('apartment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.apartmenttype')),
            ],
        ),
    ]
