# Generated by Django 5.0.1 on 2024-02-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='current_user',
            new_name='user',
        ),
    ]
