# Generated by Django 5.0.1 on 2024-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallocation',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
    ]
