# Generated by Django 5.0.1 on 2024-02-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_roomstatuschange_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomstatuschange',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
