# Generated by Django 5.0.1 on 2024-02-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='valid_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='identification_number',
            new_name='valid_id',
        ),
    ]
