# Generated by Django 5.0.1 on 2024-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_address_user_valid_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='valid_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
